config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'articles/ali'
  get "articles/hey"
  resources :articles do
    resources :comments
  end
  root 'welcome#index'  
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord   
    
    validates :name,:text, 
    presence: true,
    length: { minimum: 3 ,maximum:10}
    has_many :comments,dependent: :destroy
    validates :name,presence:true,
    length: { minimum: 3}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    http_basic_authenticate_with name: "ali",password: "admin", except: [:index, :show]
    def ali
    puts "Ali function"    
    @article = Article.new
    end
    
    def index
        @articles = Article.all
    end
    def edit
        @article = Article.find(params[:id])
    end
    def show
        @article = Article.find(params[:id])
    end
    def create
        @article = Article.new(article_params)
        # p "Article## #{@article.inspect}"
        # p "Params :-#{params[:article].inspect}"
        if @article.save
        # p "Article2 #{@article.inspect}"
            redirect_to @article
        else
            render articles_ali_path
        end
    end
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
    end
    def destroy
        @article=Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end
    private
      def article_params
          params.require(:article).permit(:name, :text)
      end

    def new
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name:  "ali",password:"ali",only: :destroy
        
        def index
            @articles = Article.all
        end
       
       
        def create
            @article=Article.find(params[:article_id])
            @comment=@article.comments.create(comment_params)
            if @article.save
            # p "Article2 #{@article.inspect}"
                redirect_to @article
            else
                render articles_ali_path
            end
        end
      
        def destroy
            @article=Article.find(params[:article_id])
            @comment=@article.comments.find(params[:id])
            @comment.destroy
            redirect_to articles_path(@article)
        end
        private
          def comment_params
              params.require(:comment).permit(:commenter, :body)
          end
    
        def new
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    p "Number of methods"
    p WelcomeController.methods.count
    p ApplicationController.superclass.superclass.superclass.superclass
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
=form_with(model: @article, local: true) do |form|
  -if @article.errors.any? 
    #eror_explanation
      %h4 
        =pluralize(@article.errors.count,"error") 
        prohibited this article from being saved:
      %ul 
        -@article.errors.full_messages.each do |msg|
          %li=msg  
  %p
    = form.label "Enter your Name"
    %br
    = form.text_field :name
 
  %p
    = form.label "Enter your text here.."
    %br
    = form.text_area :text
  %p
    = form.submit 


  

app/views/articles/ali.html.haml
<h1>Register yourself for upcoming event</h1>
=render 'form'

=link_to 'Back to Main Page', articles_path
  

app/views/articles/edit.html.haml
<h1>Edit your blog here..</h1>
=render 'form'
=link_to 'Back to Main Page', articles_path

app/views/articles/index.html.haml
%h2=link_to 'Create New Article', articles_ali_path
%table 
 %tr 
  %th Id  
  %th Name  
  %th Text 
  %th{:colspan => "3"} Link
 -@articles.each do |article|
  %tr 
   %td=article.id
   %td=article.name  
   %td=article.text
   %td=link_to 'Show', article_path(article)
   %td=link_to 'Edit', edit_article_path(article)
   %td=link_to 'Delete', article_path(article),
    method: :delete,
    data: { confirm: 'Are you sure?' } 
     

 

app/views/articles/show.html.haml
%p 
  %strong Name: 
  = @article.name 
%p 
  %strong Text: 
  = @article.text

%h2 Comments
-@@j=0
-@article.comments.each do |comment|
  =render comment
=@article.comments.class
%h4 Add a comment :
=render 'comments/form'
%a
  =link_to 'Index', articles_path
%h3
  =link_to 'Edit', edit_article_path(@article)

app/views/comments/_comment.html.haml
-if comment.commenter!=""
  %p ------#{@@j+=1}-------->
  %p
    %strong Commenter:
    =comment.commenter
  %p
    %strong Comment:
    =comment.body
  %p
    =link_to 'Delete Comment',[comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.haml
=form_with(model: [ @article,@article.comments.build ], locale:true) do |form| 
  %p 
  =form.label :commenter
  =form.text_field :commenter 
  %p 
  =form.label :body
  =form.text_area :body
  %p
  =form.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/422.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The change you wanted was rejected (422)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  .rails-default-error-page {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  .rails-default-error-page div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  .rails-default-error-page div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  .rails-default-error-page h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  .rails-default-error-page div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body class="rails-default-error-page">
  <!-- This file lives in public/422.html -->
  <div class="dialog">
    <div>
      <h1>The change you wanted was rejected.</h1>
      <p>Maybe you tried to change something you didn't have access to.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

app/views/welcome/index.html.haml
%h3 Hey Ali
%p How are you?
=link_to 'Create',articles_ali_path
%br
%br
=link_to 'My_Blog',articles_path
-# =link_to '',articles_ali_path